# ShellCommand: https://github.com/XUJINKAI/ShellCommand 

- Command: http://127.0.0.1:4000
  Name: Browser

- Command: wsl -- bundle exec jekyll serve -H 0.0.0.0 -P 4000 --trace --watch --config _config.yml
  Name: jekyll serve
