# site
title: JK的博客
description: ^_^
description-under: "<span style='color: rgba(255, 255, 255, 0.92); text-shadow: -1px 0 rgba(0, 0, 0, 0.26), 0 1px rgba(0, 0, 0, 0.26), 1px 0 rgba(0, 0, 0, 0.26), 0 -1px rgba(0, 0, 0, 0.26);'>本博新地址：<a href='http://xujinkai.net' style='color: rgba(255, 255, 255, 0.92);'>xujinkai.net</a></span>"
url: http://xujinkai.net
domain: xujinkai.net

#owner
owner:
  name: XUJINKAI
  gavatar: /img/jk.png
  email: jack777@xujinkai.net
  direct_print: 
  # http://fortawesome.github.io/Font-Awesome/3.2.1/icons/
  fonts-links:
    github: https://github.com/XUJINKAI
    tumblr: 
    weibo: http://weibo.com/johnkale
    zhihu: https://www.zhihu.com/people/xxxjin
  links: [
  ['test-blog', 'http://t.xujinkai.net'],
  ]
# links
links: [
  ["biic-test", "http://140.114.27.242/~Eval/cn", "_blank"],
  ["GitHub", "https://github.com/XUJINKAI", "_blank"],
  ["潘学文博客", "http://www.panxw.com", "_blank"],
]
# Top navbar
left_nav: [
]
right_nav: [
  ["HOME", "/"],
  ["POSTS", "/posts/"],
  ["ABOUT","/about"],
  # ["NOTE", "http://xujinkai.tumblr.com"],
  # ["FORK", "https://github.com/XUJINKAI/XUJINKAI.github.io"]
]

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
exclude: ["*.lnk", "*.bat"]

# Outputting
# DO NOT use date as url AND change timezone,
# or post would missing after upload
permalink: /posts/:title
timezone: Europe/Amsterdam
paginate_path: "page/:num"
paginate: 5
recent_limit: 7
show_rss: true

# comment
# serve: disqus, duoshuo
comment:
  serve: disqus
  disqus:
    id: xujinkai
  duoshuo:
    id: xujinkai

# analytics
# serve: ga(google), 
analytics:
  serve: ga
  ga:
    id: UA-52509591-2

# blugs
gems:
 - jekyll-paginate
