title: XUJINKAI
author: XUJINKAI
description: XUJINKAI 的个人主页
hostname: xujinkai.net
domain: https://xujinkai.net
github-repo: https://github.com/XUJINKAI/XUJINKAI.github.io

# github metadata
repository: XUJINKAI/XUJINKAI.github.io

# MUST change or delete these value
ga: UA-52509591-2
ga4: G-4Q0MVTQ7HL
disqus: xujinkai

# Conversion
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      disable : true
encoding: utf-8
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - .shellcommand.yaml

# Outputting
# DO NOT use date as url AND change timezone,
# or post would missing after upload
permalink: /posts/:title
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at

last-modified-at:
  date-format: '%d-%b-%y'
